version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - "5434:5432"
    environment:
      DATABASE_HOST: "127.0.0.1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "books"
    